// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe39CK-g0ZznussQKKa_XZTkXCpkHxTy0',
    appId: '1:916648429815:web:44c75d3c8602a5a85c6bf2',
    messagingSenderId: '916648429815',
    projectId: 'bluetoothri505',
    authDomain: 'bluetoothri505.firebaseapp.com',
    databaseURL: 'https://bluetoothri505.firebaseio.com',
    storageBucket: 'bluetoothri505.appspot.com',
    measurementId: 'G-V3EYB3BEH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndAiKMpAyBm8f4HfMVtfSx8iSQhHy0Ck',
    appId: '1:916648429815:android:ed6bb70c3258719c5c6bf2',
    messagingSenderId: '916648429815',
    projectId: 'bluetoothri505',
    databaseURL: 'https://bluetoothri505.firebaseio.com',
    storageBucket: 'bluetoothri505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfqxq7LzqkxSOLbkpzRdLUof5GW0qIYZs',
    appId: '1:916648429815:ios:aef3d40f33fd49fb5c6bf2',
    messagingSenderId: '916648429815',
    projectId: 'bluetoothri505',
    databaseURL: 'https://bluetoothri505.firebaseio.com',
    storageBucket: 'bluetoothri505.appspot.com',
    androidClientId: '916648429815-51ut1hs1vgommtjgtjlctodntfqgk3pd.apps.googleusercontent.com',
    iosClientId: '916648429815-d7gf47u2sp16lqjttjfqm4dc2lbcvhbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.genSoportes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfqxq7LzqkxSOLbkpzRdLUof5GW0qIYZs',
    appId: '1:916648429815:ios:aef3d40f33fd49fb5c6bf2',
    messagingSenderId: '916648429815',
    projectId: 'bluetoothri505',
    databaseURL: 'https://bluetoothri505.firebaseio.com',
    storageBucket: 'bluetoothri505.appspot.com',
    androidClientId: '916648429815-51ut1hs1vgommtjgtjlctodntfqgk3pd.apps.googleusercontent.com',
    iosClientId: '916648429815-d7gf47u2sp16lqjttjfqm4dc2lbcvhbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.genSoportes',
  );
}
